# Generated by Django 5.0.7 on 2024-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passport_number",
            field=models.CharField(max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
